spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Chat?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: Wlstldbs1!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
